// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RatesParsingWeb.Storage;

namespace RatesParsingWeb.Migrations
{
    [DbContext(typeof(BankRatesContext))]
    [Migration("20200121203633_SeedBanksWithTightCurrency")]
    partial class SeedBanksWithTightCurrency
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RatesParsingWeb.Domain.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankUrl")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("RatesUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrencyId = 64,
                            Name = "National Bank of Georgia",
                            RatesUrl = "https://www.nbg.gov.ge/index.php?m=582&lng=eng"
                        },
                        new
                        {
                            Id = 2,
                            CurrencyId = 124,
                            Name = "National Bank of Poland",
                            RatesUrl = "https://www.nbp.pl/homen.aspx?f=/kursy/RatesA.html"
                        },
                        new
                        {
                            Id = 3,
                            CurrencyId = 127,
                            Name = "The Central Bank of the Russian Federation",
                            RatesUrl = "https://www.cbr.ru/eng/currency_base/daily/"
                        },
                        new
                        {
                            Id = 4,
                            CurrencyId = 3,
                            Name = "European Central Bank",
                            RatesUrl = "https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html"
                        });
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("NumCode")
                        .HasColumnType("int");

                    b.Property<string>("TextCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Afghani",
                            NumCode = 971,
                            TextCode = "AFN"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Euro",
                            NumCode = 978,
                            TextCode = "EUR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Lek",
                            NumCode = 8,
                            TextCode = "ALL"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Algerian Dinar",
                            NumCode = 12,
                            TextCode = "DZD"
                        },
                        new
                        {
                            Id = 6,
                            Name = "US Dollar",
                            NumCode = 840,
                            TextCode = "USD"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kwanza",
                            NumCode = 973,
                            TextCode = "AOA"
                        },
                        new
                        {
                            Id = 8,
                            Name = "East Caribbean Dollar",
                            NumCode = 951,
                            TextCode = "XCD"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Argentine Peso",
                            NumCode = 32,
                            TextCode = "ARS"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Armenian Dram",
                            NumCode = 51,
                            TextCode = "AMD"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Aruban Florin",
                            NumCode = 533,
                            TextCode = "AWG"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Australian Dollar",
                            NumCode = 36,
                            TextCode = "AUD"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Azerbaijan Manat",
                            NumCode = 944,
                            TextCode = "AZN"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Bahamian Dollar",
                            NumCode = 44,
                            TextCode = "BSD"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Bahraini Dinar",
                            NumCode = 48,
                            TextCode = "BHD"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Taka",
                            NumCode = 50,
                            TextCode = "BDT"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Barbados Dollar",
                            NumCode = 52,
                            TextCode = "BBD"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Belarusian Ruble",
                            NumCode = 933,
                            TextCode = "BYN"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Belize Dollar",
                            NumCode = 84,
                            TextCode = "BZD"
                        },
                        new
                        {
                            Id = 21,
                            Name = "CFA Franc BCEAO",
                            NumCode = 952,
                            TextCode = "XOF"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bermudian Dollar",
                            NumCode = 60,
                            TextCode = "BMD"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Indian Rupee",
                            NumCode = 356,
                            TextCode = "INR"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Ngultrum",
                            NumCode = 64,
                            TextCode = "BTN"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Boliviano",
                            NumCode = 68,
                            TextCode = "BOB"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Mvdol",
                            NumCode = 984,
                            TextCode = "BOV"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Convertible Mark",
                            NumCode = 977,
                            TextCode = "BAM"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Pula",
                            NumCode = 72,
                            TextCode = "BWP"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Norwegian Krone",
                            NumCode = 578,
                            TextCode = "NOK"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Brazilian Real",
                            NumCode = 986,
                            TextCode = "BRL"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Brunei Dollar",
                            NumCode = 96,
                            TextCode = "BND"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Bulgarian Lev",
                            NumCode = 975,
                            TextCode = "BGN"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Burundi Franc",
                            NumCode = 108,
                            TextCode = "BIF"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Cabo Verde Escudo",
                            NumCode = 132,
                            TextCode = "CVE"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Riel",
                            NumCode = 116,
                            TextCode = "KHR"
                        },
                        new
                        {
                            Id = 36,
                            Name = "CFA Franc BEAC",
                            NumCode = 950,
                            TextCode = "XAF"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Canadian Dollar",
                            NumCode = 124,
                            TextCode = "CAD"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Cayman Islands Dollar",
                            NumCode = 136,
                            TextCode = "KYD"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Chilean Peso",
                            NumCode = 152,
                            TextCode = "CLP"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Unidad de Fomento",
                            NumCode = 990,
                            TextCode = "CLF"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Yuan Renminbi",
                            NumCode = 156,
                            TextCode = "CNY"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Colombian Peso",
                            NumCode = 170,
                            TextCode = "COP"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Unidad de Valor Real",
                            NumCode = 970,
                            TextCode = "COU"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Comorian Franc ",
                            NumCode = 174,
                            TextCode = "KMF"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Congolese Franc",
                            NumCode = 976,
                            TextCode = "CDF"
                        },
                        new
                        {
                            Id = 46,
                            Name = "New Zealand Dollar",
                            NumCode = 554,
                            TextCode = "NZD"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Costa Rican Colon",
                            NumCode = 188,
                            TextCode = "CRC"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Kuna",
                            NumCode = 191,
                            TextCode = "HRK"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Cuban Peso",
                            NumCode = 192,
                            TextCode = "CUP"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Peso Convertible",
                            NumCode = 931,
                            TextCode = "CUC"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Netherlands Antillean Guilder",
                            NumCode = 532,
                            TextCode = "ANG"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Czech Koruna",
                            NumCode = 203,
                            TextCode = "CZK"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Danish Krone",
                            NumCode = 208,
                            TextCode = "DKK"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Djibouti Franc",
                            NumCode = 262,
                            TextCode = "DJF"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Dominican Peso",
                            NumCode = 214,
                            TextCode = "DOP"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Egyptian Pound",
                            NumCode = 818,
                            TextCode = "EGP"
                        },
                        new
                        {
                            Id = 57,
                            Name = "El Salvador Colon",
                            NumCode = 222,
                            TextCode = "SVC"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Nakfa",
                            NumCode = 232,
                            TextCode = "ERN"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Ethiopian Birr",
                            NumCode = 230,
                            TextCode = "ETB"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Falkland Islands Pound",
                            NumCode = 238,
                            TextCode = "FKP"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Fiji Dollar",
                            NumCode = 242,
                            TextCode = "FJD"
                        },
                        new
                        {
                            Id = 62,
                            Name = "CFP Franc",
                            NumCode = 953,
                            TextCode = "XPF"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Dalasi",
                            NumCode = 270,
                            TextCode = "GMD"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Lari",
                            NumCode = 981,
                            TextCode = "GEL"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Ghana Cedi",
                            NumCode = 936,
                            TextCode = "GHS"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Gibraltar Pound",
                            NumCode = 292,
                            TextCode = "GIP"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Quetzal",
                            NumCode = 320,
                            TextCode = "GTQ"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Pound Sterling",
                            NumCode = 826,
                            TextCode = "GBP"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Guinean Franc",
                            NumCode = 324,
                            TextCode = "GNF"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guyana Dollar",
                            NumCode = 328,
                            TextCode = "GYD"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Gourde",
                            NumCode = 332,
                            TextCode = "HTG"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Lempira",
                            NumCode = 340,
                            TextCode = "HNL"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Hong Kong Dollar",
                            NumCode = 344,
                            TextCode = "HKD"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Forint",
                            NumCode = 348,
                            TextCode = "HUF"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Iceland Krona",
                            NumCode = 352,
                            TextCode = "ISK"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Rupiah",
                            NumCode = 360,
                            TextCode = "IDR"
                        },
                        new
                        {
                            Id = 77,
                            Name = "SDR (Special Drawing Right)",
                            NumCode = 960,
                            TextCode = "XDR"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Iranian Rial",
                            NumCode = 364,
                            TextCode = "IRR"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Iraqi Dinar",
                            NumCode = 368,
                            TextCode = "IQD"
                        },
                        new
                        {
                            Id = 80,
                            Name = "New Israeli Sheqel",
                            NumCode = 376,
                            TextCode = "ILS"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Jamaican Dollar",
                            NumCode = 388,
                            TextCode = "JMD"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Yen",
                            NumCode = 392,
                            TextCode = "JPY"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Jordanian Dinar",
                            NumCode = 400,
                            TextCode = "JOD"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Tenge",
                            NumCode = 398,
                            TextCode = "KZT"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Kenyan Shilling",
                            NumCode = 404,
                            TextCode = "KES"
                        },
                        new
                        {
                            Id = 86,
                            Name = "North Korean Won",
                            NumCode = 408,
                            TextCode = "KPW"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Won",
                            NumCode = 410,
                            TextCode = "KRW"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kuwaiti Dinar",
                            NumCode = 414,
                            TextCode = "KWD"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Som",
                            NumCode = 417,
                            TextCode = "KGS"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Lao Kip",
                            NumCode = 418,
                            TextCode = "LAK"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Lebanese Pound",
                            NumCode = 422,
                            TextCode = "LBP"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Loti",
                            NumCode = 426,
                            TextCode = "LSL"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Rand",
                            NumCode = 710,
                            TextCode = "ZAR"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Liberian Dollar",
                            NumCode = 430,
                            TextCode = "LRD"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Libyan Dinar",
                            NumCode = 434,
                            TextCode = "LYD"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Swiss Franc",
                            NumCode = 756,
                            TextCode = "CHF"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Pataca",
                            NumCode = 446,
                            TextCode = "MOP"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Denar",
                            NumCode = 807,
                            TextCode = "MKD"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Malagasy Ariary",
                            NumCode = 969,
                            TextCode = "MGA"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Malawi Kwacha",
                            NumCode = 454,
                            TextCode = "MWK"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Malaysian Ringgit",
                            NumCode = 458,
                            TextCode = "MYR"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Rufiyaa",
                            NumCode = 462,
                            TextCode = "MVR"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Ouguiya",
                            NumCode = 929,
                            TextCode = "MRU"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Mauritius Rupee",
                            NumCode = 480,
                            TextCode = "MUR"
                        },
                        new
                        {
                            Id = 105,
                            Name = "ADB Unit of Account",
                            NumCode = 965,
                            TextCode = "XUA"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Mexican Peso",
                            NumCode = 484,
                            TextCode = "MXN"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Mexican Unidad de Inversion (UDI)",
                            NumCode = 979,
                            TextCode = "MXV"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Moldovan Leu",
                            NumCode = 498,
                            TextCode = "MDL"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Tugrik",
                            NumCode = 496,
                            TextCode = "MNT"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Moroccan Dirham",
                            NumCode = 504,
                            TextCode = "MAD"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Mozambique Metical",
                            NumCode = 943,
                            TextCode = "MZN"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Kyat",
                            NumCode = 104,
                            TextCode = "MMK"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Namibia Dollar",
                            NumCode = 516,
                            TextCode = "NAD"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Nepalese Rupee",
                            NumCode = 524,
                            TextCode = "NPR"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Cordoba Oro",
                            NumCode = 558,
                            TextCode = "NIO"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Naira",
                            NumCode = 566,
                            TextCode = "NGN"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Rial Omani",
                            NumCode = 512,
                            TextCode = "OMR"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Pakistan Rupee",
                            NumCode = 586,
                            TextCode = "PKR"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Balboa",
                            NumCode = 590,
                            TextCode = "PAB"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Kina",
                            NumCode = 598,
                            TextCode = "PGK"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Guarani",
                            NumCode = 600,
                            TextCode = "PYG"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Sol",
                            NumCode = 604,
                            TextCode = "PEN"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Philippine Peso",
                            NumCode = 608,
                            TextCode = "PHP"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Zloty",
                            NumCode = 985,
                            TextCode = "PLN"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Qatari Rial",
                            NumCode = 634,
                            TextCode = "QAR"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Romanian Leu",
                            NumCode = 946,
                            TextCode = "RON"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Russian Ruble",
                            NumCode = 643,
                            TextCode = "RUB"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Rwanda Franc",
                            NumCode = 646,
                            TextCode = "RWF"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Saint Helena Pound",
                            NumCode = 654,
                            TextCode = "SHP"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Tala",
                            NumCode = 882,
                            TextCode = "WST"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Dobra",
                            NumCode = 930,
                            TextCode = "STN"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Saudi Riyal",
                            NumCode = 682,
                            TextCode = "SAR"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Serbian Dinar",
                            NumCode = 941,
                            TextCode = "RSD"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Seychelles Rupee",
                            NumCode = 690,
                            TextCode = "SCR"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Leone",
                            NumCode = 694,
                            TextCode = "SLL"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Singapore Dollar",
                            NumCode = 702,
                            TextCode = "SGD"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Sucre",
                            NumCode = 994,
                            TextCode = "XSU"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Solomon Islands Dollar",
                            NumCode = 90,
                            TextCode = "SBD"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Somali Shilling",
                            NumCode = 706,
                            TextCode = "SOS"
                        },
                        new
                        {
                            Id = 140,
                            Name = "South Sudanese Pound",
                            NumCode = 728,
                            TextCode = "SSP"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Sri Lanka Rupee",
                            NumCode = 144,
                            TextCode = "LKR"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Sudanese Pound",
                            NumCode = 938,
                            TextCode = "SDG"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Surinam Dollar",
                            NumCode = 968,
                            TextCode = "SRD"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Lilangeni",
                            NumCode = 748,
                            TextCode = "SZL"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Swedish Krona",
                            NumCode = 752,
                            TextCode = "SEK"
                        },
                        new
                        {
                            Id = 146,
                            Name = "WIR Euro",
                            NumCode = 947,
                            TextCode = "CHE"
                        },
                        new
                        {
                            Id = 147,
                            Name = "WIR Franc",
                            NumCode = 948,
                            TextCode = "CHW"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Syrian Pound",
                            NumCode = 760,
                            TextCode = "SYP"
                        },
                        new
                        {
                            Id = 149,
                            Name = "New Taiwan Dollar",
                            NumCode = 901,
                            TextCode = "TWD"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Somoni",
                            NumCode = 972,
                            TextCode = "TJS"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Tanzanian Shilling",
                            NumCode = 834,
                            TextCode = "TZS"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Baht",
                            NumCode = 764,
                            TextCode = "THB"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Pa’anga",
                            NumCode = 776,
                            TextCode = "TOP"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Trinidad and Tobago Dollar",
                            NumCode = 780,
                            TextCode = "TTD"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Tunisian Dinar",
                            NumCode = 788,
                            TextCode = "TND"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Turkish Lira",
                            NumCode = 949,
                            TextCode = "TRY"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Turkmenistan New Manat",
                            NumCode = 934,
                            TextCode = "TMT"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Uganda Shilling",
                            NumCode = 800,
                            TextCode = "UGX"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Hryvnia",
                            NumCode = 980,
                            TextCode = "UAH"
                        },
                        new
                        {
                            Id = 160,
                            Name = "UAE Dirham",
                            NumCode = 784,
                            TextCode = "AED"
                        },
                        new
                        {
                            Id = 161,
                            Name = "US Dollar (Next day)",
                            NumCode = 997,
                            TextCode = "USN"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Peso Uruguayo",
                            NumCode = 858,
                            TextCode = "UYU"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Uruguay Peso en Unidades Indexadas (UI)",
                            NumCode = 940,
                            TextCode = "UYI"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Unidad Previsional",
                            NumCode = 927,
                            TextCode = "UYW"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Uzbekistan Sum",
                            NumCode = 860,
                            TextCode = "UZS"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Vatu",
                            NumCode = 548,
                            TextCode = "VUV"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Bolívar Soberano",
                            NumCode = 928,
                            TextCode = "VES"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Dong",
                            NumCode = 704,
                            TextCode = "VND"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Yemeni Rial",
                            NumCode = 886,
                            TextCode = "YER"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Zambian Kwacha",
                            NumCode = 967,
                            TextCode = "ZMW"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Zimbabwe Dollar",
                            NumCode = 932,
                            TextCode = "ZWL"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Bond Markets Unit European Composite Unit (EURCO)",
                            NumCode = 955,
                            TextCode = "XBA"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
                            NumCode = 956,
                            TextCode = "XBB"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
                            NumCode = 957,
                            TextCode = "XBC"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
                            NumCode = 958,
                            TextCode = "XBD"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Codes specifically reserved for testing purposes",
                            NumCode = 963,
                            TextCode = "XTS"
                        },
                        new
                        {
                            Id = 177,
                            Name = "The codes assigned for transactions where no currency is involved",
                            NumCode = 999,
                            TextCode = "XXX"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Gold",
                            NumCode = 959,
                            TextCode = "XAU"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Palladium",
                            NumCode = 964,
                            TextCode = "XPD"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Platinum",
                            NumCode = 962,
                            TextCode = "XPT"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Silver",
                            NumCode = 961,
                            TextCode = "XAG"
                        });
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("ExchangeRateListId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExchangeRateValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ExchangeRateListId");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.ExchangeRateList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("ExchangeRateLists");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.ParsingSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int?>("EndXpathRow")
                        .HasColumnType("int");

                    b.Property<string>("ExchangeRateXpath")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("NumberDecimalSeparator")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("NumberGroupSeparator")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("StartXpathRow")
                        .HasColumnType("int");

                    b.Property<string>("TextCodeXpath")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("UnitXpath")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("VariablePartOfXpath")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("BankId")
                        .IsUnique();

                    b.ToTable("ParsingSettings");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.Script", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("ParamsNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.TextCodeScriptAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int?>("ParsingSettingsId")
                        .HasColumnType("int");

                    b.Property<int>("ScriptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("ParsingSettingsId");

                    b.HasIndex("ScriptId");

                    b.ToTable("TextCodeScriptAssignments");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.TextCodeScriptParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TextCodeScriptAssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("TextCodeScriptAssignmentId");

                    b.ToTable("TextCodeScriptParameters");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.UnitScriptAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int?>("ParsingSettingsId")
                        .HasColumnType("int");

                    b.Property<int>("ScriptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("ParsingSettingsId");

                    b.HasIndex("ScriptId");

                    b.ToTable("UnitScriptAssignments");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.UnitScriptParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UnitScriptAssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("UnitScriptAssignmentId");

                    b.ToTable("UnitScriptParameters");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.Bank", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.Currency", "Currency")
                        .WithMany("Banks")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.ExchangeRate", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.Currency", "Currency")
                        .WithMany("ExchangeRates")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RatesParsingWeb.Domain.ExchangeRateList", "ExchangeRateList")
                        .WithMany("ExchangeRates")
                        .HasForeignKey("ExchangeRateListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.ExchangeRateList", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.Bank", "Bank")
                        .WithMany("ExchangeRateLists")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.ParsingSettings", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.Bank", "Bank")
                        .WithOne("ParsingSettings")
                        .HasForeignKey("RatesParsingWeb.Domain.ParsingSettings", "BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.TextCodeScriptAssignment", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RatesParsingWeb.Domain.ParsingSettings", null)
                        .WithMany("TextCodeScripts")
                        .HasForeignKey("ParsingSettingsId");

                    b.HasOne("RatesParsingWeb.Domain.Script", "Script")
                        .WithMany()
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.TextCodeScriptParameter", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.TextCodeScriptAssignment", "TextCodeScriptAssignment")
                        .WithMany("ScriptParameters")
                        .HasForeignKey("TextCodeScriptAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.UnitScriptAssignment", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RatesParsingWeb.Domain.ParsingSettings", null)
                        .WithMany("UnitScripts")
                        .HasForeignKey("ParsingSettingsId");

                    b.HasOne("RatesParsingWeb.Domain.Script", "Script")
                        .WithMany("ScriptAssignments")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.UnitScriptParameter", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.UnitScriptAssignment", "UnitScriptAssignment")
                        .WithMany("ScriptParameters")
                        .HasForeignKey("UnitScriptAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
