// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RatesParsingWeb.Storage;

namespace RatesParsingWeb.Migrations
{
    [DbContext(typeof(BankRatesContext))]
    [Migration("20200125195651_SetTypeToExchangeRates")]
    partial class SetTypeToExchangeRates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RatesParsingWeb.Domain.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankUrl")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("RatesUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("SwiftCode")
                        .IsRequired()
                        .HasColumnType("nchar(11)")
                        .IsFixedLength(true)
                        .HasMaxLength(11);

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankUrl = "https://www.nbg.gov.ge",
                            CurrencyId = 981,
                            Name = "National Bank of Georgia",
                            RatesUrl = "https://www.nbg.gov.ge/index.php?m=582&lng=eng",
                            SwiftCode = "BNLNGE22XXX"
                        },
                        new
                        {
                            Id = 2,
                            BankUrl = "https://www.nbp.pl",
                            CurrencyId = 985,
                            Name = "National Bank of Poland",
                            RatesUrl = "https://www.nbp.pl/homen.aspx?f=/kursy/RatesA.html",
                            SwiftCode = "NBPLPLPWBAN"
                        },
                        new
                        {
                            Id = 3,
                            BankUrl = "https://www.cbr.ru",
                            CurrencyId = 643,
                            Name = "The Central Bank of the Russian Federation",
                            RatesUrl = "https://www.cbr.ru/eng/currency_base/daily/",
                            SwiftCode = "CBRFRUMMXXX"
                        },
                        new
                        {
                            Id = 4,
                            BankUrl = "https://www.ecb.europa.eu",
                            CurrencyId = 978,
                            Name = "European Central Bank",
                            RatesUrl = "https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html",
                            SwiftCode = "ECBFDEFFEUM"
                        });
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("NumCode")
                        .HasColumnType("int");

                    b.Property<string>("TextCode")
                        .IsRequired()
                        .HasColumnType("nchar(3)")
                        .IsFixedLength(true)
                        .HasMaxLength(3);

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 971,
                            Name = "Afghani",
                            TextCode = "AFN"
                        },
                        new
                        {
                            Id = 978,
                            Name = "Euro",
                            TextCode = "EUR"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Lek",
                            TextCode = "ALL"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Algerian Dinar",
                            TextCode = "DZD"
                        },
                        new
                        {
                            Id = 840,
                            Name = "US Dollar",
                            TextCode = "USD"
                        },
                        new
                        {
                            Id = 973,
                            Name = "Kwanza",
                            TextCode = "AOA"
                        },
                        new
                        {
                            Id = 951,
                            Name = "East Caribbean Dollar",
                            TextCode = "XCD"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Argentine Peso",
                            TextCode = "ARS"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Armenian Dram",
                            TextCode = "AMD"
                        },
                        new
                        {
                            Id = 533,
                            Name = "Aruban Florin",
                            TextCode = "AWG"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Australian Dollar",
                            TextCode = "AUD"
                        },
                        new
                        {
                            Id = 944,
                            Name = "Azerbaijan Manat",
                            TextCode = "AZN"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Bahamian Dollar",
                            TextCode = "BSD"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Bahraini Dinar",
                            TextCode = "BHD"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Taka",
                            TextCode = "BDT"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Barbados Dollar",
                            TextCode = "BBD"
                        },
                        new
                        {
                            Id = 933,
                            Name = "Belarusian Ruble",
                            TextCode = "BYN"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Belize Dollar",
                            TextCode = "BZD"
                        },
                        new
                        {
                            Id = 952,
                            Name = "CFA Franc BCEAO",
                            TextCode = "XOF"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Bermudian Dollar",
                            TextCode = "BMD"
                        },
                        new
                        {
                            Id = 356,
                            Name = "Indian Rupee",
                            TextCode = "INR"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Ngultrum",
                            TextCode = "BTN"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Boliviano",
                            TextCode = "BOB"
                        },
                        new
                        {
                            Id = 984,
                            Name = "Mvdol",
                            TextCode = "BOV"
                        },
                        new
                        {
                            Id = 977,
                            Name = "Convertible Mark",
                            TextCode = "BAM"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Pula",
                            TextCode = "BWP"
                        },
                        new
                        {
                            Id = 578,
                            Name = "Norwegian Krone",
                            TextCode = "NOK"
                        },
                        new
                        {
                            Id = 986,
                            Name = "Brazilian Real",
                            TextCode = "BRL"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Brunei Dollar",
                            TextCode = "BND"
                        },
                        new
                        {
                            Id = 975,
                            Name = "Bulgarian Lev",
                            TextCode = "BGN"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Burundi Franc",
                            TextCode = "BIF"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Cabo Verde Escudo",
                            TextCode = "CVE"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Riel",
                            TextCode = "KHR"
                        },
                        new
                        {
                            Id = 950,
                            Name = "CFA Franc BEAC",
                            TextCode = "XAF"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Canadian Dollar",
                            TextCode = "CAD"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Cayman Islands Dollar",
                            TextCode = "KYD"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Chilean Peso",
                            TextCode = "CLP"
                        },
                        new
                        {
                            Id = 990,
                            Name = "Unidad de Fomento",
                            TextCode = "CLF"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Yuan Renminbi",
                            TextCode = "CNY"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Colombian Peso",
                            TextCode = "COP"
                        },
                        new
                        {
                            Id = 970,
                            Name = "Unidad de Valor Real",
                            TextCode = "COU"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Comorian Franc ",
                            TextCode = "KMF"
                        },
                        new
                        {
                            Id = 976,
                            Name = "Congolese Franc",
                            TextCode = "CDF"
                        },
                        new
                        {
                            Id = 554,
                            Name = "New Zealand Dollar",
                            TextCode = "NZD"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Costa Rican Colon",
                            TextCode = "CRC"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Kuna",
                            TextCode = "HRK"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Cuban Peso",
                            TextCode = "CUP"
                        },
                        new
                        {
                            Id = 931,
                            Name = "Peso Convertible",
                            TextCode = "CUC"
                        },
                        new
                        {
                            Id = 532,
                            Name = "Netherlands Antillean Guilder",
                            TextCode = "ANG"
                        },
                        new
                        {
                            Id = 203,
                            Name = "Czech Koruna",
                            TextCode = "CZK"
                        },
                        new
                        {
                            Id = 208,
                            Name = "Danish Krone",
                            TextCode = "DKK"
                        },
                        new
                        {
                            Id = 262,
                            Name = "Djibouti Franc",
                            TextCode = "DJF"
                        },
                        new
                        {
                            Id = 214,
                            Name = "Dominican Peso",
                            TextCode = "DOP"
                        },
                        new
                        {
                            Id = 818,
                            Name = "Egyptian Pound",
                            TextCode = "EGP"
                        },
                        new
                        {
                            Id = 222,
                            Name = "El Salvador Colon",
                            TextCode = "SVC"
                        },
                        new
                        {
                            Id = 232,
                            Name = "Nakfa",
                            TextCode = "ERN"
                        },
                        new
                        {
                            Id = 230,
                            Name = "Ethiopian Birr",
                            TextCode = "ETB"
                        },
                        new
                        {
                            Id = 238,
                            Name = "Falkland Islands Pound",
                            TextCode = "FKP"
                        },
                        new
                        {
                            Id = 242,
                            Name = "Fiji Dollar",
                            TextCode = "FJD"
                        },
                        new
                        {
                            Id = 953,
                            Name = "CFP Franc",
                            TextCode = "XPF"
                        },
                        new
                        {
                            Id = 270,
                            Name = "Dalasi",
                            TextCode = "GMD"
                        },
                        new
                        {
                            Id = 981,
                            Name = "Lari",
                            TextCode = "GEL"
                        },
                        new
                        {
                            Id = 936,
                            Name = "Ghana Cedi",
                            TextCode = "GHS"
                        },
                        new
                        {
                            Id = 292,
                            Name = "Gibraltar Pound",
                            TextCode = "GIP"
                        },
                        new
                        {
                            Id = 320,
                            Name = "Quetzal",
                            TextCode = "GTQ"
                        },
                        new
                        {
                            Id = 826,
                            Name = "Pound Sterling",
                            TextCode = "GBP"
                        },
                        new
                        {
                            Id = 324,
                            Name = "Guinean Franc",
                            TextCode = "GNF"
                        },
                        new
                        {
                            Id = 328,
                            Name = "Guyana Dollar",
                            TextCode = "GYD"
                        },
                        new
                        {
                            Id = 332,
                            Name = "Gourde",
                            TextCode = "HTG"
                        },
                        new
                        {
                            Id = 340,
                            Name = "Lempira",
                            TextCode = "HNL"
                        },
                        new
                        {
                            Id = 344,
                            Name = "Hong Kong Dollar",
                            TextCode = "HKD"
                        },
                        new
                        {
                            Id = 348,
                            Name = "Forint",
                            TextCode = "HUF"
                        },
                        new
                        {
                            Id = 352,
                            Name = "Iceland Krona",
                            TextCode = "ISK"
                        },
                        new
                        {
                            Id = 360,
                            Name = "Rupiah",
                            TextCode = "IDR"
                        },
                        new
                        {
                            Id = 960,
                            Name = "SDR (Special Drawing Right)",
                            TextCode = "XDR"
                        },
                        new
                        {
                            Id = 364,
                            Name = "Iranian Rial",
                            TextCode = "IRR"
                        },
                        new
                        {
                            Id = 368,
                            Name = "Iraqi Dinar",
                            TextCode = "IQD"
                        },
                        new
                        {
                            Id = 376,
                            Name = "New Israeli Sheqel",
                            TextCode = "ILS"
                        },
                        new
                        {
                            Id = 388,
                            Name = "Jamaican Dollar",
                            TextCode = "JMD"
                        },
                        new
                        {
                            Id = 392,
                            Name = "Yen",
                            TextCode = "JPY"
                        },
                        new
                        {
                            Id = 400,
                            Name = "Jordanian Dinar",
                            TextCode = "JOD"
                        },
                        new
                        {
                            Id = 398,
                            Name = "Tenge",
                            TextCode = "KZT"
                        },
                        new
                        {
                            Id = 404,
                            Name = "Kenyan Shilling",
                            TextCode = "KES"
                        },
                        new
                        {
                            Id = 408,
                            Name = "North Korean Won",
                            TextCode = "KPW"
                        },
                        new
                        {
                            Id = 410,
                            Name = "Won",
                            TextCode = "KRW"
                        },
                        new
                        {
                            Id = 414,
                            Name = "Kuwaiti Dinar",
                            TextCode = "KWD"
                        },
                        new
                        {
                            Id = 417,
                            Name = "Som",
                            TextCode = "KGS"
                        },
                        new
                        {
                            Id = 418,
                            Name = "Lao Kip",
                            TextCode = "LAK"
                        },
                        new
                        {
                            Id = 422,
                            Name = "Lebanese Pound",
                            TextCode = "LBP"
                        },
                        new
                        {
                            Id = 426,
                            Name = "Loti",
                            TextCode = "LSL"
                        },
                        new
                        {
                            Id = 710,
                            Name = "Rand",
                            TextCode = "ZAR"
                        },
                        new
                        {
                            Id = 430,
                            Name = "Liberian Dollar",
                            TextCode = "LRD"
                        },
                        new
                        {
                            Id = 434,
                            Name = "Libyan Dinar",
                            TextCode = "LYD"
                        },
                        new
                        {
                            Id = 756,
                            Name = "Swiss Franc",
                            TextCode = "CHF"
                        },
                        new
                        {
                            Id = 446,
                            Name = "Pataca",
                            TextCode = "MOP"
                        },
                        new
                        {
                            Id = 807,
                            Name = "Denar",
                            TextCode = "MKD"
                        },
                        new
                        {
                            Id = 969,
                            Name = "Malagasy Ariary",
                            TextCode = "MGA"
                        },
                        new
                        {
                            Id = 454,
                            Name = "Malawi Kwacha",
                            TextCode = "MWK"
                        },
                        new
                        {
                            Id = 458,
                            Name = "Malaysian Ringgit",
                            TextCode = "MYR"
                        },
                        new
                        {
                            Id = 462,
                            Name = "Rufiyaa",
                            TextCode = "MVR"
                        },
                        new
                        {
                            Id = 929,
                            Name = "Ouguiya",
                            TextCode = "MRU"
                        },
                        new
                        {
                            Id = 480,
                            Name = "Mauritius Rupee",
                            TextCode = "MUR"
                        },
                        new
                        {
                            Id = 965,
                            Name = "ADB Unit of Account",
                            TextCode = "XUA"
                        },
                        new
                        {
                            Id = 484,
                            Name = "Mexican Peso",
                            TextCode = "MXN"
                        },
                        new
                        {
                            Id = 979,
                            Name = "Mexican Unidad de Inversion (UDI)",
                            TextCode = "MXV"
                        },
                        new
                        {
                            Id = 498,
                            Name = "Moldovan Leu",
                            TextCode = "MDL"
                        },
                        new
                        {
                            Id = 496,
                            Name = "Tugrik",
                            TextCode = "MNT"
                        },
                        new
                        {
                            Id = 504,
                            Name = "Moroccan Dirham",
                            TextCode = "MAD"
                        },
                        new
                        {
                            Id = 943,
                            Name = "Mozambique Metical",
                            TextCode = "MZN"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Kyat",
                            TextCode = "MMK"
                        },
                        new
                        {
                            Id = 516,
                            Name = "Namibia Dollar",
                            TextCode = "NAD"
                        },
                        new
                        {
                            Id = 524,
                            Name = "Nepalese Rupee",
                            TextCode = "NPR"
                        },
                        new
                        {
                            Id = 558,
                            Name = "Cordoba Oro",
                            TextCode = "NIO"
                        },
                        new
                        {
                            Id = 566,
                            Name = "Naira",
                            TextCode = "NGN"
                        },
                        new
                        {
                            Id = 512,
                            Name = "Rial Omani",
                            TextCode = "OMR"
                        },
                        new
                        {
                            Id = 586,
                            Name = "Pakistan Rupee",
                            TextCode = "PKR"
                        },
                        new
                        {
                            Id = 590,
                            Name = "Balboa",
                            TextCode = "PAB"
                        },
                        new
                        {
                            Id = 598,
                            Name = "Kina",
                            TextCode = "PGK"
                        },
                        new
                        {
                            Id = 600,
                            Name = "Guarani",
                            TextCode = "PYG"
                        },
                        new
                        {
                            Id = 604,
                            Name = "Sol",
                            TextCode = "PEN"
                        },
                        new
                        {
                            Id = 608,
                            Name = "Philippine Peso",
                            TextCode = "PHP"
                        },
                        new
                        {
                            Id = 985,
                            Name = "Zloty",
                            TextCode = "PLN"
                        },
                        new
                        {
                            Id = 634,
                            Name = "Qatari Rial",
                            TextCode = "QAR"
                        },
                        new
                        {
                            Id = 946,
                            Name = "Romanian Leu",
                            TextCode = "RON"
                        },
                        new
                        {
                            Id = 643,
                            Name = "Russian Ruble",
                            TextCode = "RUB"
                        },
                        new
                        {
                            Id = 646,
                            Name = "Rwanda Franc",
                            TextCode = "RWF"
                        },
                        new
                        {
                            Id = 654,
                            Name = "Saint Helena Pound",
                            TextCode = "SHP"
                        },
                        new
                        {
                            Id = 882,
                            Name = "Tala",
                            TextCode = "WST"
                        },
                        new
                        {
                            Id = 930,
                            Name = "Dobra",
                            TextCode = "STN"
                        },
                        new
                        {
                            Id = 682,
                            Name = "Saudi Riyal",
                            TextCode = "SAR"
                        },
                        new
                        {
                            Id = 941,
                            Name = "Serbian Dinar",
                            TextCode = "RSD"
                        },
                        new
                        {
                            Id = 690,
                            Name = "Seychelles Rupee",
                            TextCode = "SCR"
                        },
                        new
                        {
                            Id = 694,
                            Name = "Leone",
                            TextCode = "SLL"
                        },
                        new
                        {
                            Id = 702,
                            Name = "Singapore Dollar",
                            TextCode = "SGD"
                        },
                        new
                        {
                            Id = 994,
                            Name = "Sucre",
                            TextCode = "XSU"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Solomon Islands Dollar",
                            TextCode = "SBD"
                        },
                        new
                        {
                            Id = 706,
                            Name = "Somali Shilling",
                            TextCode = "SOS"
                        },
                        new
                        {
                            Id = 728,
                            Name = "South Sudanese Pound",
                            TextCode = "SSP"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Sri Lanka Rupee",
                            TextCode = "LKR"
                        },
                        new
                        {
                            Id = 938,
                            Name = "Sudanese Pound",
                            TextCode = "SDG"
                        },
                        new
                        {
                            Id = 968,
                            Name = "Surinam Dollar",
                            TextCode = "SRD"
                        },
                        new
                        {
                            Id = 748,
                            Name = "Lilangeni",
                            TextCode = "SZL"
                        },
                        new
                        {
                            Id = 752,
                            Name = "Swedish Krona",
                            TextCode = "SEK"
                        },
                        new
                        {
                            Id = 947,
                            Name = "WIR Euro",
                            TextCode = "CHE"
                        },
                        new
                        {
                            Id = 948,
                            Name = "WIR Franc",
                            TextCode = "CHW"
                        },
                        new
                        {
                            Id = 760,
                            Name = "Syrian Pound",
                            TextCode = "SYP"
                        },
                        new
                        {
                            Id = 901,
                            Name = "New Taiwan Dollar",
                            TextCode = "TWD"
                        },
                        new
                        {
                            Id = 972,
                            Name = "Somoni",
                            TextCode = "TJS"
                        },
                        new
                        {
                            Id = 834,
                            Name = "Tanzanian Shilling",
                            TextCode = "TZS"
                        },
                        new
                        {
                            Id = 764,
                            Name = "Baht",
                            TextCode = "THB"
                        },
                        new
                        {
                            Id = 776,
                            Name = "Pa’anga",
                            TextCode = "TOP"
                        },
                        new
                        {
                            Id = 780,
                            Name = "Trinidad and Tobago Dollar",
                            TextCode = "TTD"
                        },
                        new
                        {
                            Id = 788,
                            Name = "Tunisian Dinar",
                            TextCode = "TND"
                        },
                        new
                        {
                            Id = 949,
                            Name = "Turkish Lira",
                            TextCode = "TRY"
                        },
                        new
                        {
                            Id = 934,
                            Name = "Turkmenistan New Manat",
                            TextCode = "TMT"
                        },
                        new
                        {
                            Id = 800,
                            Name = "Uganda Shilling",
                            TextCode = "UGX"
                        },
                        new
                        {
                            Id = 980,
                            Name = "Hryvnia",
                            TextCode = "UAH"
                        },
                        new
                        {
                            Id = 784,
                            Name = "UAE Dirham",
                            TextCode = "AED"
                        },
                        new
                        {
                            Id = 997,
                            Name = "US Dollar (Next day)",
                            TextCode = "USN"
                        },
                        new
                        {
                            Id = 858,
                            Name = "Peso Uruguayo",
                            TextCode = "UYU"
                        },
                        new
                        {
                            Id = 940,
                            Name = "Uruguay Peso en Unidades Indexadas (UI)",
                            TextCode = "UYI"
                        },
                        new
                        {
                            Id = 927,
                            Name = "Unidad Previsional",
                            TextCode = "UYW"
                        },
                        new
                        {
                            Id = 860,
                            Name = "Uzbekistan Sum",
                            TextCode = "UZS"
                        },
                        new
                        {
                            Id = 548,
                            Name = "Vatu",
                            TextCode = "VUV"
                        },
                        new
                        {
                            Id = 928,
                            Name = "Bolívar Soberano",
                            TextCode = "VES"
                        },
                        new
                        {
                            Id = 704,
                            Name = "Dong",
                            TextCode = "VND"
                        },
                        new
                        {
                            Id = 886,
                            Name = "Yemeni Rial",
                            TextCode = "YER"
                        },
                        new
                        {
                            Id = 967,
                            Name = "Zambian Kwacha",
                            TextCode = "ZMW"
                        },
                        new
                        {
                            Id = 932,
                            Name = "Zimbabwe Dollar",
                            TextCode = "ZWL"
                        },
                        new
                        {
                            Id = 955,
                            Name = "Bond Markets Unit European Composite Unit (EURCO)",
                            TextCode = "XBA"
                        },
                        new
                        {
                            Id = 956,
                            Name = "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
                            TextCode = "XBB"
                        },
                        new
                        {
                            Id = 957,
                            Name = "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
                            TextCode = "XBC"
                        },
                        new
                        {
                            Id = 958,
                            Name = "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
                            TextCode = "XBD"
                        },
                        new
                        {
                            Id = 963,
                            Name = "Codes specifically reserved for testing purposes",
                            TextCode = "XTS"
                        },
                        new
                        {
                            Id = 999,
                            Name = "The codes assigned for transactions where no currency is involved",
                            TextCode = "XXX"
                        },
                        new
                        {
                            Id = 959,
                            Name = "Gold",
                            TextCode = "XAU"
                        },
                        new
                        {
                            Id = 964,
                            Name = "Palladium",
                            TextCode = "XPD"
                        },
                        new
                        {
                            Id = 962,
                            Name = "Platinum",
                            TextCode = "XPT"
                        },
                        new
                        {
                            Id = 961,
                            Name = "Silver",
                            TextCode = "XAG"
                        });
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("ExchangeRateListId")
                        .HasColumnType("int");

                    b.Property<decimal>("ExchangeRateValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("ExchangeRateListId");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.ExchangeRateList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("ExchangeRateLists");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.ParsingSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int?>("EndXpathRow")
                        .HasColumnType("int");

                    b.Property<string>("ExchangeRateXpath")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("NumberDecimalSeparator")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("NumberGroupSeparator")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("StartXpathRow")
                        .HasColumnType("int");

                    b.Property<string>("TextCodeXpath")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("UnitXpath")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("VariablePartOfXpath")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("BankId")
                        .IsUnique();

                    b.ToTable("ParsingSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankId = 1,
                            EndXpathRow = 36,
                            ExchangeRateXpath = "//*[@id='article']/table/tr/td/center/table[1]/tr[$VARIABLE]/td[3]",
                            NumberDecimalSeparator = ".",
                            NumberGroupSeparator = ",",
                            StartXpathRow = 2,
                            TextCodeXpath = "//*[@id='article']/table/tr/td/center/table[1]/tr[$VARIABLE]/td[2]",
                            UnitXpath = "//*[@id='article']/table/tr/td/center/table[1]/tr[$VARIABLE]/td[2]",
                            VariablePartOfXpath = "$VARIABLE"
                        });
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.Script", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("ParamsNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.TextCodeScriptAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int?>("ParsingSettingsId")
                        .HasColumnType("int");

                    b.Property<int>("ScriptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("ParsingSettingsId");

                    b.HasIndex("ScriptId");

                    b.ToTable("TextCodeScriptAssignments");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.TextCodeScriptParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TextCodeScriptAssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("TextCodeScriptAssignmentId");

                    b.ToTable("TextCodeScriptParameters");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.UnitScriptAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int?>("ParsingSettingsId")
                        .HasColumnType("int");

                    b.Property<int>("ScriptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("ParsingSettingsId");

                    b.HasIndex("ScriptId");

                    b.ToTable("UnitScriptAssignments");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.UnitScriptParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UnitScriptAssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("UnitScriptAssignmentId");

                    b.ToTable("UnitScriptParameters");
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.Bank", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.Currency", "Currency")
                        .WithMany("Banks")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.ExchangeRate", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.Currency", "Currency")
                        .WithMany("ExchangeRates")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RatesParsingWeb.Domain.ExchangeRateList", "ExchangeRateList")
                        .WithMany("ExchangeRates")
                        .HasForeignKey("ExchangeRateListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.ExchangeRateList", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.Bank", "Bank")
                        .WithMany("ExchangeRateLists")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.ParsingSettings", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.Bank", "Bank")
                        .WithOne("ParsingSettings")
                        .HasForeignKey("RatesParsingWeb.Domain.ParsingSettings", "BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.TextCodeScriptAssignment", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RatesParsingWeb.Domain.ParsingSettings", null)
                        .WithMany("TextCodeScripts")
                        .HasForeignKey("ParsingSettingsId");

                    b.HasOne("RatesParsingWeb.Domain.Script", "Script")
                        .WithMany()
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.TextCodeScriptParameter", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.TextCodeScriptAssignment", "TextCodeScriptAssignment")
                        .WithMany("ScriptParameters")
                        .HasForeignKey("TextCodeScriptAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.UnitScriptAssignment", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RatesParsingWeb.Domain.ParsingSettings", null)
                        .WithMany("UnitScripts")
                        .HasForeignKey("ParsingSettingsId");

                    b.HasOne("RatesParsingWeb.Domain.Script", "Script")
                        .WithMany("ScriptAssignments")
                        .HasForeignKey("ScriptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RatesParsingWeb.Domain.UnitScriptParameter", b =>
                {
                    b.HasOne("RatesParsingWeb.Domain.UnitScriptAssignment", "UnitScriptAssignment")
                        .WithMany("ScriptParameters")
                        .HasForeignKey("UnitScriptAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
