//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatesParsingWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RatesParsingWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] FakeExchangeRates {
            get {
                object obj = ResourceManager.GetObject("FakeExchangeRates", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ISO_4217 Pblshd=&quot;2018-08-29&quot;&gt;
        ///	&lt;CcyTbl&gt;
        ///		&lt;CcyNtry&gt;
        ///			&lt;CtryNm&gt;AFGHANISTAN&lt;/CtryNm&gt;
        ///			&lt;CcyNm&gt;Afghani&lt;/CcyNm&gt;
        ///			&lt;Ccy&gt;AFN&lt;/Ccy&gt;
        ///			&lt;CcyNbr&gt;971&lt;/CcyNbr&gt;
        ///			&lt;CcyMnrUnts&gt;2&lt;/CcyMnrUnts&gt;
        ///		&lt;/CcyNtry&gt;
        ///		&lt;CcyNtry&gt;
        ///			&lt;CtryNm&gt;ÅLAND ISLANDS&lt;/CtryNm&gt;
        ///			&lt;CcyNm&gt;Euro&lt;/CcyNm&gt;
        ///			&lt;Ccy&gt;EUR&lt;/Ccy&gt;
        ///			&lt;CcyNbr&gt;978&lt;/CcyNbr&gt;
        ///			&lt;CcyMnrUnts&gt;2&lt;/CcyMnrUnts&gt;
        ///		&lt;/CcyNtry&gt;
        ///		&lt;CcyNtry&gt;
        ///			&lt;CtryNm&gt;ALBANIA&lt;/CtryNm&gt;
        ///			&lt;CcyNm&gt;Lek&lt;/CcyNm&gt;
        ///			&lt;Ccy&gt;ALL&lt;/Ccy&gt;
        ///			&lt;C [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ISO4217 {
            get {
                return ResourceManager.GetString("ISO4217", resourceCulture);
            }
        }
    }
}
